#include <gmp.h>
#include <mpfr.h>
#include <stdio.h> /* fprintf, fopen, fclose, */
#include <sys/types.h> /* pid_t */
#include <sys/wait.h> /* wait */
#include <unistd.h> /* execve, fork, daemon */
#include <stdlib.h> /* exit, free, mktemp */
#include <errno.h>
#include "plot.h"
#include "expression.h"
#include "main.h"

void plotTree(node *tree, mpfr_t a, mpfr_t b, unsigned long int points, mp_prec_t prec) {
  mpfr_t x, y, step;
  FILE *file;


  mpfr_init2(x, prec);
  mpfr_init2(step, prec);
  mpfr_init2(y, prec);
 
  file = fopen("/tmp/arenaireplot.p", "w");
  fprintf(file, "# Gnuplot script generated by ArenairePlot\n");
  fprintf(file, "set xrange [%1.50e:%1.50e]\n", mpfr_get_d(a, GMP_RNDD),mpfr_get_d(b, GMP_RNDU));
  fprintf(file, "plot \"/tmp/data_arenaireplot.dat\" using 1:2 with lines t \"\"\n");
  fclose(file);

  file = fopen("/tmp/data_arenaireplot.dat", "w");
  mpfr_sub(step, b, a, GMP_RNDN);
  mpfr_div_ui(step, step, points, GMP_RNDN);
 
  if (mpfr_sgn(step) == 0) {
    evaluate(y,tree,a,prec);
    printValue(&y,prec);
    printf("\n");
    mpfr_clear(x); mpfr_clear(y); mpfr_clear(step);
    return;
  }

  if (mpfr_sgn(step) < 0) {
    printMessage(1,"Warning: the interval is empty\n");
    mpfr_clear(x); mpfr_clear(y); mpfr_clear(step);
    return;
  }

  if (evaluateConstantExpression(y,tree,prec)) {
    printValue(&y,prec);
    printf("\n");
    mpfr_clear(x); mpfr_clear(y); mpfr_clear(step);
    return;
  }
 
  for(mpfr_set(x,a,GMP_RNDN); mpfr_lessequal_p(x,b); mpfr_add(x,x,step,GMP_RNDN)) {
    evaluate(y,tree,x,prec);
    fprintf(file, "%1.50e\t%1.50e\n", mpfr_get_d(x, GMP_RNDN), mpfr_get_d(y, GMP_RNDN));
  }
 
  fclose(file);
  mpfr_clear(x); mpfr_clear(y); mpfr_clear(step);

  if (fork()==0) {
    daemon(0,1);
    execlp("gnuplot", "gnuplot", "-persist", "/tmp/arenaireplot.p", NULL);
    perror("An error occured when calling gnuplot ");
    exit(1);
  }
  else wait(NULL);

  return;
}
