<a name="autosimplify"></a> 
<div class="divName"> 
<h2 class="name">Name:</h2> <?php linkTo("command","autosimplify","autosimplify");?> 
<span class="smallDescription">activates, deactivates or inspects the value of the automatic simplification state variable 
</span> 
</div> 
<div class="divUsage"> 
<h2 class="category">Usage: </h2> 
<span class="commandline"><?php linkTo("command","autosimplify","autosimplify");?> = <span class="arg">activation value</span> : <span class="type">on|off</span> -&gt; <span class="type">void</span></span> 
<span class="commandline"><?php linkTo("command","autosimplify","autosimplify");?> = <span class="arg">activation value</span> ! : <span class="type">on|off</span> -&gt; <span class="type">void</span></span> 
<span class="commandline"><?php linkTo("command","autosimplify","autosimplify");?> : <span class="type">on|off</span></span> 
 
</div> 
<div class="divParameters"> 
<h2 class="category">Parameters: </h2> 
<ul> 
<li><span class="arg">activation value</span> represents <?php linkTo("command","on","on");?> or <?php linkTo("command","off","off");?>, i.e. activation or deactivation</li> 
</ul> 
</div> 
<div class="divDescription"> 
<h2 class="category">Description: </h2><ul> 
<li>An assignment <?php linkTo("command","autosimplify","autosimplify");?> = <span class="arg">activation value</span>, where <span class="arg">activation value</span> 
is one of <?php linkTo("command","on","on");?> or <?php linkTo("command","off","off");?>, activates respectively deactivates the 
automatic safe simplification of expressions of functions generated by 
the evaluation of commands or in argument of other commands. 
<br><br> 
Sollya commands like <?php linkTo("command","remez","remez");?>, <?php linkTo("command","taylor","taylor");?> or <?php linkTo("command","rationalapprox","rationalapprox");?> sometimes 
produce expressions that can be simplified. Constant subexpressions 
can be evaluated to dyadic floating-point numbers, monomials with 
coefficients 0 can be eliminated. Further, expressions 
indicated by the user perform better in many commands when simplified 
before being passed in argument to a command. When the automatic 
simplification of expressions is activated, Sollya automatically 
performs a safe (not value changing) simplification process on such 
expressions. 
<br><br> 
The automatic generation of subexpressions can be annoying, in 
particular if it takes too much time for not enough benefit. Further the 
user might want to inspect the structure of the expression tree 
returned by a command. In this case, the automatic simplification 
should be deactivated. 
<br><br> 
If the assignment <?php linkTo("command","autosimplify","autosimplify");?> = <span class="arg">activation value</span> is followed by an 
exclamation mark, no message indicating the new state is 
displayed. Otherwise the user is informed of the new state of the 
global mode by an indication. 
</ul> 
</div> 
<div class="divExamples"> 
<div class="divExample"> 
<h2 class="category">Example 1: </h2> 
&nbsp;&nbsp;&nbsp;&gt; autosimplify = on !;<br> 
&nbsp;&nbsp;&nbsp;&gt; print(x - x);<br> 
&nbsp;&nbsp;&nbsp;0<br> 
&nbsp;&nbsp;&nbsp;&gt; autosimplify = off ;<br> 
&nbsp;&nbsp;&nbsp;Automatic pure tree simplification has been deactivated.<br> 
&nbsp;&nbsp;&nbsp;&gt; print(x - x);<br> 
&nbsp;&nbsp;&nbsp;x - x<br> 
</div> 
<div class="divExample"> 
<h2 class="category">Example 2: </h2> 
&nbsp;&nbsp;&nbsp;&gt; autosimplify = on !; <br> 
&nbsp;&nbsp;&nbsp;&gt; print(rationalapprox(sin(pi/5.9),7));<br> 
&nbsp;&nbsp;&nbsp;0.5<br> 
&nbsp;&nbsp;&nbsp;&gt; autosimplify = off !; <br> 
&nbsp;&nbsp;&nbsp;&gt; print(rationalapprox(sin(pi/5.9),7));<br> 
&nbsp;&nbsp;&nbsp;1 / 2<br> 
</div> 
</div> 
<div class="divSeeAlso"> 
<span class="category">See also: </span><?php linkTo("command","print","print");?>, <?php linkTo("command","prec","prec");?>, <?php linkTo("command","points","points");?>, <?php linkTo("command","diam","diam");?>, <?php linkTo("command","display","display");?>, <?php linkTo("command","verbosity","verbosity");?>, <?php linkTo("command","canonical","canonical");?>, <?php linkTo("command","taylorrecursions","taylorrecursions");?>, <?php linkTo("command","timing","timing");?>, <?php linkTo("command","fullparentheses","fullparentheses");?>, <?php linkTo("command","midpointmode","midpointmode");?>, <?php linkTo("command","hopitalrecursions","hopitalrecursions");?>, <?php linkTo("command","remez","remez");?>, <?php linkTo("command","rationalapprox","rationalapprox");?>, <?php linkTo("command","taylor","taylor");?> 
</div> 
